### ISSUE TITLE
Gregicality 0.24.0 crashed

### ISSUE THREAD

**Issue by Shepherd23333** [GregTechCEu/gregicality-legacy#646]
https://paste.ubuntu.com/p/nRtq5g2gpR/

**Comment by TechLord22** [comment]
Did you build Gregicality from the source code and use it in a normal instance? This error usually only appears when you build a jar using the wrong task for regular use. When building jars outside of the development environment, you need to use the Gradle `build` task instead of `jar`.

**Comment by LegendaryCrystalFox** [comment]
I'm getting the same crash: https://pastebin.com/JpTisvZW

**Comment by TechLord22** [comment]
In that case, can you try regenerating your configs? Some of the names changed in this update and might be causing problems.

**Comment by LegendaryCrystalFox** [comment]
Ok, I'll do that when I get the chance and I'll let you know what happens

**Comment by TheRealKamisama** [comment]
Same problem here, resolved after regenerating config files.
Thanks for your help.
