### ISSUE TITLE
Large multi machines force recipes involving programmed circuit to run on max parallel

### ISSUE THREAD

**Issue by WisdomAbel** [GregTechCEu/gregicality-legacy#650]
To be clear. If i use EV Large Mixer to make incoloy ma-956 dust , the machine will not run if the provided ingredients are less than 16x the ingredients required by the recipe.

Same issues also occur on large bender.

Using Gregicality v0.24.0-final
Can confirm not involved in 0.23

**Comment by earlywyrm** [comment]
any update on that fix? thx in advance

**Comment by TechLord22** [comment]
It has been quite a while... A new version was supposed to go live and be released on CurseForge back in Februrary, but I don't have the ability to actually upload builds, and the others who can are not really available for right now (and were not back then either), so you really have two options going forwards:

1) Build the latest version of the mod yourself, which is not difficult but also annoying to have to do.

2) Download and use the following two forks of GCYL and GTCE by the Technological Journey modpack team, which has those fixes and more for the GCYL-GTCE ecosystem. They are continuing GCYL and related gt work for GTCE. There are some more major changes to Nuclear Processing and Circuits in these forks, so it may break some existing processing setups. The changelogs don't have *everything* in them so if you have more questions, I'd recommend asking the TJ team on their discord.
You can find the two mods here: <https://www.curseforge.com/minecraft/mc-mods/gregicality-tjfork> and <https://www.curseforge.com/minecraft/mc-mods/gtce-tj-edition>. Note that the GCYL fork requires the CE fork as well.

**Comment by earlywyrm** [comment]
you're a saint, thanks :)

**Comment by TechLord22** [comment]
Glad to help out 👍🏻. I'll close this issue for now as it is technically fixed in dev for the time being.
